export default [
  {
    week: 1,
    title: 'Talking About Family and Friends',
    cards: [
      { en: 'Nouns', es: 'Sustantivos' },
      { en: 'Verbs', es: 'Verbos' },
      { en: 'Adjectives', es: 'Adjetivos' },
      { en: 'Year', es: 'Año' },
      { en: 'Man', es: 'Hombre (m)' },
      { en: 'Woman', es: 'Mujer (f)' },
      { en: 'House', es: 'Casa (f)' },
      { en: 'Son', es: 'Hijo' },
      { en: 'Daughter', es: 'Hija' },
      { en: 'Father', es: 'Padre (m)' },
      { en: 'Mother', es: 'Madre (f)' },
      { en: 'Brother', es: 'Hermano' },
      { en: 'Sister', es: 'Hermana' },
      { en: 'Grandfather', es: 'Abuelo' },
      { en: 'Grandmother', es: 'Abuela' },
      { en: 'Name', es: 'Nombre (m)' },
      { en: 'Age', es: 'Edad (f)' },
      { en: 'Family', es: 'Familia (f)' },
      { en: 'Relation', es: 'Relación (f)' },
      { en: 'Friend (m)', es: 'Amigo' },
      { en: 'Friend (f)', es: 'Amiga' },
      { en: 'Education', es: 'Educación (f)' },
      { en: 'To be', es: 'Ser' },
      { en: 'To have', es: 'Tener' },
      { en: 'To pass', es: 'Pasar' },
      { en: 'To talk', es: 'Hablar' },
      { en: 'To call', es: 'Llamar' },
      { en: 'To be born', es: 'Nacer' },
      { en: 'To ask (about)', es: 'Preguntar (por)' },
      { en: 'To study', es: 'Estudiar' },
      { en: 'To live', es: 'Vivir' },
      { en: 'To exist', es: 'Existir' },
      { en: 'Big, large', es: 'Grande' },
      { en: 'Small, little (m)', es: 'Pequeño' },
      { en: 'Small, little (f)', es: 'Pequeña' },
      { en: 'Older', es: 'Mayor' },
      { en: 'Younger', es: 'Menor' },
      { en: 'Special', es: 'Especial' },
      { en: 'Unique (m)', es: 'Único' },
      { en: 'Unique (f)', es: 'Única' },
      { en: 'Same (m)', es: 'Mismo' },
      { en: 'Same (f)', es: 'Misma' },
      { en: 'Ours (m)', es: 'Nuestro' },
      { en: 'Ours (f)', es: 'Nuestra' },
      { en: 'Alive', es: 'Vivo' },
      { en: 'Dead', es: 'Muerto' },
      { en: 'Hardworker (m)', es: 'Trabajador' },
      { en: 'Hardworker (f)', es: 'Trabajadora' },
    ],
  },
  {
    week: 2,
    title: 'Bar',
    cards: [
      {
        en: 'Grandmother',
        es: 'Abuela',
      },
      {
        en: 'Grandfather',
        es: 'Abuelo',
      },
    ],
  },
]
